.apex/src/objects/Vacation_Request__c.object
<CustomObject>
    <description>Object to store vacation request data</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>EndDate</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Vacation_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestType__c</fullName>
        <label>RequestType</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vacation</fullName>
                    <default>true</default>
                    <label>Vacation</label>
                </value>
                <value>
                    <fullName>Sick</fullName>
                </value>
                <value>
                    <fullName>Unpaid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>StartDate</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkingDays__c</fullName>
        <label>WorkingDays</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Vacation Request</label>
    <nameField>
        <label>Vacation Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vacation Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/requestTriggerTest.cls
@IsTest
public class requestTriggerTest {

	@IsTest
	static void validateRequestTrigger() {
		User user = [SELECT Id, Name, ManagerId FROM User WHERE ManagerId != null limit 1][0];
		System.runAs(user) {
			Date startDate = Date.today();
			Date endDate = Date.today().addDays(10);
			Vacation_Request__c request = new Vacation_Request__c(
					Status__c = 'New', EndDate__c = endDate,
					StartDate__c  = startDate,
					RequestType__c = 'Sick'
			);

			insert request;

			request = [SELECT Id, Name, Manager__c, WorkingDays__c
									FROM Vacation_Request__c WHERE CreatedById =: user.Id];

			System.assertEquals('Request from ' + user.Name, request.Name);
			System.assertEquals(user.ManagerId, request.Manager__c);
			System.assertEquals(DateController.getWorkingDays(startDate, endDate), request.WorkingDays__c);
		}
	}
}