.apex/src/objects/Vacation_Request__c.object
<CustomObject>
    <description>Object to store vacation request data</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>EndDate</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Vacation_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestType__c</fullName>
        <label>RequestType</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vacation</fullName>
                    <default>true</default>
                    <label>Vacation</label>
                </value>
                <value>
                    <fullName>Sick</fullName>
                </value>
                <value>
                    <fullName>Unpaid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>StartDate</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Vacation Request</label>
    <nameField>
        <label>Vacation Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vacation Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RequestControllerTest.cls
@IsTest
public class RequestControllerTest {

	@IsTest
	static void validateGetRequests() {

		User user = [SELECT Id, Name FROM User LIMIT 1][0];

		User manager;
		for (User temp : [SELECT Id, Name FROM User]) {
			if (temp.Id != user.Id) {
				manager = temp;
				break;
			}
		}

		Vacation_Request__c r = new Vacation_Request__c();
		r.Status__c = 'New';
		r.EndDate__c = Date.newInstance(2022, 8, 23);
		r.StartDate__c  = Date.newInstance(2022, 8, 2);
		r.RequestType__c = 'Sick';
		r.Manager__c = manager.Id;
		r.Manager__r = manager;

		insert r;

		System.runAs(user) {

			for (Integer i = 0 ; i < 3; i++) {
				Vacation_Request__c request = new Vacation_Request__c(
						Status__c = 'New', EndDate__c = Date.newInstance(2022, 8, 23),
						StartDate__c  = Date.newInstance(2022, 8, 2),
						RequestType__c = 'Sick',
						Manager__c = manager.Id,
						Manager__r = manager
				);

				insert request;
			}

			List<RequestsController.RequestWrapper> allRequests = RequestsController.getRequests(false);
			List<RequestsController.RequestWrapper> myRequests = RequestsController.getRequests(true);

			System.assertEquals(true, allRequests.size() >= myRequests.size());

			if (myRequests.size() >= 1) {
				Boolean allWithSameUser = true;
				Id prevRequest = myRequests.get(0).userId;
				for (RequestsController.RequestWrapper myRequest : myRequests) {
					if (prevRequest != myRequest.userId) {
						allWithSameUser = false;
						break;
					}
				}

				System.assertEquals(false, allWithSameUser);
			}
		}
	}
}